trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: StageA
  jobs:
  - job: JobA
    steps:
    - script: |
        echo "This is job Foo."
        echo "##vso[task.setvariable variable=doThing;isOutput=true]Yes" #The variable doThing is set to Yes
      name: DetermineResult
    - script: echo $(DetermineResult.doThing)
      name: echovar
  - job: JobA_2
    dependsOn: JobA
    condition: eq(dependencies.JobA.outputs['DetermineResult.doThing'], 'Yes')
    steps:
    - script: |
        echo "This is job Bar."
#job JB from stage B runs if DetermineResult task set doThing variable n stage A
- stage: StageB
  dependsOn: StageA
  jobs:
  - job: JobB
    condition: eq(stageDependencies.StageA.JobA.outputs['DetermineResult.doThing'], 'Yes') #map doThing and check if true
    variables:
      varFromStageA: $[ stageDependencies.StageA.JobA.outputs['DetermineResult.doThing'] ]
    steps:
    - bash: echo "Hello world stage B first job"
    - script: echo $(varFromStageA)